Settings:
  uses:
    DAMAGE: true
    ARMOR: true
    MAXHEALTH: true
    SPEED: true
    JUMPPOWER: true
  multiplier:
    DAMAGE: 1
    ARMOR: 0.5
    MAXHEALTH: 1
    SPEED: 0.01
    JUMPPOWER: 0.005


RLV:
  1: 100
  2: 200
  3: 300
  4: 400
  5: 500
  6: 600
  7: 700
  8: 800
  9: 900
  10: 1000